{% extends 'partial/layoutIndex.swig' %}

{% block title %}豆米的博客{% endblock %}

{% block style %}
{% parent %}
<link rel='stylesheet' href='/styles/aboutDouMi.css'>
{% endblock %}

{% block content %}
<section class='wrapper'>
  <img src='/images/under-construction.jpg'>
</section>
<footer class='footer'>
  <div>
    Copyright © <a href='/'>豆米博客</a>. 2016 • All rights reserved. | 浙ICP备15041819号-1
  </div>
</footer>
{% endblock %}

{% block script %}

{% endblock %}
